version: '3'
services:
  web:
    image: docker.io/bureaucratschoice/onpremchat-gpu:0.8.2
    restart: unless-stopped
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"] 
    environment:
      - SUPERTOKEN=PLEASE_CHANGE_THIS_PLEASE # Really please change this, otherwise everyone reading the github repo can get access.
      - MODEL_DOWNLOAD_URL=https://huggingface.co/bartowski/google_gemma-3-12b-it-GGUF/resolve/main/google_gemma-3-12b-it-Q6_K.gguf
      - MODEL_BIN_PATH=/models/google_gemma-3-12b-it-Q6_K.gguf
      - GPU_LAYERS=33 
      - HUGGINGFACE_HUB_CACHE=/models/hub
      - HF_DATASETS_OFFLINE=1
    volumes:
      - ./models:/models
      - ./config:/config
      - ./web/src/static:/app/static
    ports:
      - 8000:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600





