version: '3'
services:
  web:
    image: docker.io/bureaucratschoice/onpremchat-gpu:0.8.2
    restart: unless-stopped
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"] 
    environment:
      - SUPERTOKEN=PLEASE_CHANGE_THIS_PLEASE # Really please change this, otherwise everyone reading the github repo can get access.
      - MODEL_DOWNLOAD_URL=https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-GGUF/resolve/main/Mistral-Nemo-Instruct-2407-Q5_K_L.gguf
      - MODEL_BIN_PATH=/models/Mistral-Nemo-Instruct-2407-Q5_K_L.gguf
      - GPU_LAYERS=-1 
      - NUMBER_OF_TOKENS =4096
      - NUMBER_OF_TOKENS_PDF=3800
      - SUMMARIZER =simple
      - CHATPROMPT=Sei hilfreich!
      - APP_TITLE=MWICHT
      - HUGGINGFACE_HUB_CACHE=/models/hub
      - HF_DATASETS_OFFLINE=1
    volumes:
      - ./models:/models
      - ./config:/config
      - ./web/src/static:/app/static
    ports:
      - 8000:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600





