version: '3'
services:
  web:
    image: docker.io/bureaucratschoice/onpremchat:0.5
    restart: unless-stopped
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"] 
    environment:
      - SUPERTOKEN=PLEASE_CHANGE_THIS_PLEASE # Really please change this, otherwise everyone reading the github repo can get access.
      - MODEL_DOWNLOAD_URL=https://huggingface.co/TheBloke/em_german_leo_mistral-GGUF/resolve/main/em_german_leo_mistral.Q5_K_S.gguf
      - MODEL_BIN_PATH=/models/em_german_leo_mistral.Q5_K_S.gguf
    volumes:
      - ./models:/models
      - ./config:/config
    ports:
      - 8000:80
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600





