version: '3.8'
services:
  web:
    build: 
      context: ../web
      dockerfile: ./build_app_gpu/Dockerfile
    image:
      bureaucratschoice/onpremchat:latest-gpu
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"] 
    environment:
      - SUPERTOKEN=PLEASE_CHANGE_THIS_PLEASE # Really please change this, otherwise everyone reading the github repo can get access.
    volumes:
      - ./models:/models
      - ./config:/config
    ports:
      - 8000:80






